steps:
  - name: node
    entrypoint: yarn
    dir: "cost-calc"
    args: ["install"]
  - name: node
    entrypoint: yarn
    dir: "cost-calc"
    args: ["build"]
  - name: gcr.io/cloud-builders/gsutil
    dir: "cost-calc"
    args: ["cp", "dist/*", "gs://${_DEPLOY_BUCKET}"]
